---
- name: Deploy Scientific Calculator Container
  hosts: mytarget
  become: yes
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: prajyotshende/spe_calculator
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: spe_calculator
        image: prajyotshende/spe_calculator:latest
        state: started
        restart_policy: always

    - name: Remove existing container(If running)
      docker_container:
        name: spe_calculator
        state: absent
        force_kill: yes

    - name: Running Container
      shell: docker run -it -d --name prajyotshende/spe_calculator /bin/bash
