---
- name: Deploy Scientific Calculator Container
  hosts: mytarget
  become: yes
  tasks:
    - name: Pull latest Docker image
      community.docker.docker_image:
        name: prajyotshende/spe_calculator
        tag: latest
        source: pull

    - name: Stop and remove existing container (if running)
      community.docker.docker_container:
        name: scientific-calculator
        state: absent
        force_kill: yes

    - name: Run the new container
      community.docker.docker_container:
        name: scientific-calculator
        image: prajyotshende/spe_calculator:latest
        state: started
        restart_policy: always
        ports:
          - "9090:8080"
        interactive: yes
        tty: yes

#
#    - name: Running Container
#      shell: docker run -it -d --name prajyotshende_spe_calculator /bin/bash
